config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  mount Privy::API => '/api'
  root 'messages#new'

  mount DiscordEngine::Engine => '/discord'

  resources :messages, only: %i[show new create], param: :uuid
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/uuidable.rb
module Uuidable
  extend ActiveSupport::Concern

  included do
    before_create :generate_uuid
  end

  private

  def generate_uuid
    loop do
      uuid = UUID7.generate
      next if self.class.exists?(uuid:)

      self.uuid = uuid
      break
    end
  end
end

app/models/discord_message.rb
class DiscordMessage < ExternalMessage
end

app/models/external_message.rb
class ExternalMessage < ApplicationRecord
  belongs_to :message

  validates :external_id, presence: true, uniqueness: { scope: %i[channel_id] }
  validates :channel_id, presence: true
  validates :type, presence: true
end

app/models/interface.rb
class Interface < ApplicationRecord
  INTERNAL_SOURCES = %i[web api].freeze
  EXTERNAL_SOURCES = [:discord_guild].freeze

  enum source: { discord_guild: 0, web: 1, api: 2 }

  has_many :messages, dependent: :destroy

  validates :source, presence: true
  validates :external_id, presence: true, uniqueness: { scope: :source }, unless: :internal?
  validate :unique_source, if: :internal?

  scope :api, -> { find_by(source: :api) }
  scope :web, -> { find_by(source: :web) }

  def internal?
    return false unless source

    INTERNAL_SOURCES.include?(source.to_sym)
  end

  private

  def unique_source
    return unless self.class.where(source:).where.not(id:).exists?

    errors.add(:source, 'internal sources must be unique')
  end
end

app/models/message.rb
class Message < ApplicationRecord
  include Uuidable

  enum expiration_type: {
    hour: '0',
    hours: '1',
    day: '2',
    days: '3',
    week: '4',
    weeks: '5',
    month: '6',
    months: '7',
    visit: '8',
    visits: '9'
  }

  before_create :set_dates
  after_update :set_updated_at

  has_many :message_visits, dependent: :destroy
  has_one :external_message, dependent: :destroy

  belongs_to :interface

  has_rich_text :content, encrypted: true

  validates :content, presence: true, unless: :expired
  validates :expiration_limit, numericality: { only_integer: true, greater_than: 0 }, presence: true
  validates :expiration_type, presence: true
  validates :expired, inclusion: { in: [true, false] }, allow_nil: false

  def expiration
    MessageExpiration.new(expiration_limit, expiration_type)
  end

  def available?
    return time_based_available? if expiration.time_based?
    return visit_based_available? if expiration.visits_based?

    raise Messages::ExpirationTypeError, self
  end

  private

  def set_dates
    date = Time.current.utc
    self.created_at = date
    self.updated_at = date
  end

  def set_updated_at
    self.updated_at = Time.current.utc
  end

  def time_based_available?
    current_time = Time.current.utc
    expires_at = created_at + expiration.limit.public_send(expiration.type)
    return true if current_time <= expires_at

    false
  end

  def visit_based_available?
    return true if message_visits_count.to_i < expiration.limit

    false
  end
end

app/models/message_visit.rb
class MessageVisit < ApplicationRecord
  belongs_to :message, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :redirect_with_error
  rescue_from Messages::ExpiredError, with: :redirect_with_error
  rescue_from Messages::CreationFailed, with: :redirect_with_error

  def redirect_with_error(error)
    flash[:alert] = error.message
    redirect_to root_path
  end

  def redirect_with_validation_error(error)
    flash[:alert] = error.record.errors.full_messages.join(', ')
    redirect_to root_path
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    creator = Messages::Creator.new(params: message_params, source: :web)
    creator.call
    @message = creator.message

    respond_to(&:turbo_stream)
  end

  def show
    @content = Messages::Reader.new(message).read_message
  end

  private

  def message_params
    params.require(:message).permit(:content, :expiration_limit, :expiration_type)
  end

  def message
    @message ||= Message.find_by!(uuid: params[:uuid])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown_to_html(text)
    renderer = HTMLwithPygments.new(filter_html: true, hard_wrap: true)
    markdown = Redcarpet::Markdown.new(renderer,
                                       { fenced_code_blocks: true, autolink: true, tables: true })
    sanitize(markdown.render(text))
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Privy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js", defer: true %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css", media: "all" %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div
        class="absolute w-full text-center"
        data-controller="blank-element"
        data-blank-element-target="containerToClear"
        data-action="click->blank-element#clearContainer"
      >
        <span
          class="inline-block w-full text-md <%= type == 'notice' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700' %> py-2"
        >
          <%= msg %>
        </span>
        </div>
      </div>
    <% end %>
    <main class="min-h-screen flex items-start justify-start md:items-center md:justify-center p-0 md:p-4">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/create.turbo_stream.erb
<%= turbo_stream.replace(
  'new_message_form',
  partial: 'partials/confirmation',
  locals: { message: @message }
)%>

app/views/messages/new.html.erb
<div
  id="new_message_form"
  class="h-screen
        md:h-full
        flex
        flex-col
        justify-start
        gap-6
        md:gap-8
        px-4
        py-8
        md:p-8
        w-full
        md:w-3/5"
>
  <h1 class="text-3xl font-bold text-gray-800 border-b-2 border-gray-700 flex-1">
    Create a New Message
  </h1>

  <%= render 'partials/form', message: @message %>
</div>

app/views/messages/show.html.erb
<div
  data-controller="clipboard"
  class="h-screen
      md:h-full
      flex
      flex-col
      justify-start
      gap-6
      md:gap-8
      px-4
      py-8
      md:p-8
      w-full
      md:w-3/5"
>
  <h1 class="text-3xl font-bold text-gray-800 border-b-2 border-gray-700">
    Message says:
  </h1>


  <div data-action="click->clipboard#selectContent"
    class="w-full flex flex-col gap-4 md:gap-6"
  >
    <div class="prose max-w-full bg-gray-100 border border-gray-300 rounded-lg py-2 px-4">
      <%= markdown_to_html(@content.to_plain_text) %>
    </div>

    <%= link_to(
      "Create a new message",
      root_url,
      turbo: true,
      class: "self-start
              inline-flex
              items-center
              justify-center
              h-10
              py-2
              px-5
              border
              border-transparent
              shadow-sm
              text-sm
              font-medium
              rounded-full
              text-white
              bg-indigo-600
              hover:bg-indigo-700
              hover:scale-105
              transition-transform
              focus:outline-none
              focus:ring-2
              focus:ring-offset-2
              focus:ring-indigo-500"
    ) %>
  </div>
</div>

app/views/partials/_confirmation.html.erb
<div
  id="new_message_form"
  data-controller="clipboard"
  class="h-screen
        md:h-full
        flex
        flex-col
        justify-start
        gap-6
        md:gap-8
        px-4
        py-8
        md:p-8
        w-full
        md:w-3/5"
>
  <h1 class="text-4xl font-bold text-gray-800 mb-6 border-b-2">
    Message Created!
  </h1>

  <div class="w-full flex flex-col gap-2">
    <p class="text-2xl text-gray-800">
      Your message's link:
    </p>
    <input
      data-clipboard-target="source"
      type="text"
      data-action="click->clipboard#selectContent"
      value="<%= message_url(uuid: @message.uuid) %>"
      readonly
      class="w-full bg-gray-100 border border-gray-300 rounded-lg p-2 mt-2 mb-4"
    >
  </div>

  <div class="min-w-full flex flex-col gap-2 md:gap-4 md:flex-row justify-between">
    <button
      id="copy-link-button"
      type="button"
      data-clipboard-target="triggerButton"
      data-action="clipboard#copy"
      class="block items-center justify-center py-3 px-6 border border-transparent shadow-sm text-base font-medium rounded-full text-white bg-indigo-600 hover:bg-indigo-700 hover:scale-105 transition-transform focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
    >
      Copy link
    </button>
    <%= link_to "New message", root_path, class: "inline-flex items-center justify-center py-3 px-6 border border-transparent shadow-sm text-base font-medium rounded-full text-white bg-indigo-600 hover:bg-indigo-700 hover:scale-105 transition-transform focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
</div>

app/views/partials/_form.html.erb
<%= form_with(
  model: @message,
  local: true,
  data: { controller: "expiration", action: "change->expiration#updateExpirationTypeOptions" },
  class: "h-screen md:h-auto flex"
) do |form| %>
  <div class="flex flex-col min-w-full h-full justify-start gap-4 md:gap-6">
    <div class="flex flex-col gap-2 md:gap-4">
      <%= form.label :content, class: "block text-sm font-medium text-gray-700" %>
      <%= form.hidden_field :content, id: "message-content" %>
      <textarea id="markdown-editor" class="block w-full p-3 border border-gray-300 rounded-md shadow-sm"></textarea>
    </div>

    <div class="w-full flex flex-col gap-4">
      <%= form.label "expires message in:", class: "block text-sm font-medium text-gray-700" %>

      <div class="w-full flex justify-between">
        <div class="flex gap-2">
          <div
            data-expiration-target="expirationLimit"
          >
            <%= form.select(
              :expiration_limit,
              options_for_select((1..12).to_a, @message.expiration_limit),
              class: "mt-1
                      block
                      w-full
                      p-3
                      border
                      border-gray-300
                      rounded-md
                      shadow-sm
                      focus:ring-indigo-500
                      focus:border-indigo-500
                      text-sm
                      md:text-base"
            ) %>
          </div>

          <div
            data-expiration-target="expirationType"
          >
            <%= form.select(
              :expiration_type,
              [],
              class: "mt-1
                      block
                      w-full
                      p-3
                      border
                      border-gray-300
                      rounded-md
                      shadow-sm
                      focus:ring-indigo-500
                      focus:border-indigo-500
                      text-sm
                      md:text-base"
            ) %>
          </div>
        </div>

        <%= form.submit(
          "Create Message",
          class: "self-end
                  inline-flex
                  items-center
                  justify-center
                  h-10
                  py-2
                  px-5
                  border
                  border-transparent
                  shadow-sm
                  text-sm
                  font-medium
                  rounded-full
                  text-white
                  bg-indigo-600
                  hover:bg-indigo-700
                  hover:scale-105
                  transition-transform
                  focus:outline-none
                  focus:ring-2
                  focus:ring-offset-2
                  focus:ring-indigo-500"
        ) %>
      </div>
    </div>
  </div>
<% end %>